-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 16:18:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banda` (
  `idBanda` INT NOT NULL,
  `nome` CHAR(128) NULL,
  `biografia` CHAR(128) NULL,
  `origem` CHAR(128) NULL,
  `anoFormacao` YEAR(4) NULL,
  `data_cadastro` DATETIME NULL,
  `direitosAutorais` CHAR(64) NULL,
  PRIMARY KEY (`idBanda`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idAlbum` INT NOT NULL,
  `anoLancamento` YEAR(4) NULL,
  `gravadora` CHAR(64) NULL,
  `observacoes` CHAR(128) NULL,
  `titulo` CHAR(64) NULL,
  `banda_idBanda` INT NOT NULL,
  PRIMARY KEY (`idAlbum`, `banda_idBanda`),
  INDEX `fk_album_banda_idx` (`banda_idBanda` ASC) VISIBLE,
  CONSTRAINT `fk_album_banda`
    FOREIGN KEY (`banda_idBanda`)
    REFERENCES `mydb`.`banda` (`idBanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estiloMusical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estiloMusical` (
  `idEstiloMusical` INT NOT NULL,
  `descricao` CHAR(128) NULL,
  `nome` VARCHAR(25) NULL,
  PRIMARY KEY (`idEstiloMusical`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musica` (
  `idMusica` INT NOT NULL,
  `duracaoSegundos` INT NULL,
  `compositor` CHAR(128) NULL,
  `letraResumo` CHAR(128) NULL,
  `titulo` CHAR(128) NULL,
  `album_idAlbum` INT NOT NULL,
  `faixa` CHAR(64) NULL,
  `musicacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMusica`, `album_idAlbum`),
  INDEX `fk_musica_album1_idx` (`album_idAlbum` ASC) VISIBLE,
  CONSTRAINT `fk_musica_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `mydb`.`album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artista` (
  `idArtista` INT NOT NULL,
  `nome` CHAR(64) NULL,
  `dataNascimento` DATETIME NULL,
  `origem` CHAR(64) NULL,
  `biografia` CHAR(64) NULL,
  `dataCadastro` DATETIME NULL,
  `artistacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrumento` (
  `idInstrumento` INT NOT NULL,
  `nome` CHAR(64) NULL,
  `descricao` CHAR(128) NULL,
  PRIMARY KEY (`idInstrumento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artista_instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artista_instrumento` (
  `artista_idArtista` INT NOT NULL,
  `instrumento_idInstrumento` INT NOT NULL,
  PRIMARY KEY (`artista_idArtista`, `instrumento_idInstrumento`),
  INDEX `fk_artista_has_instrumento_instrumento1_idx` (`instrumento_idInstrumento` ASC) VISIBLE,
  INDEX `fk_artista_has_instrumento_artista1_idx` (`artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_artista_has_instrumento_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `mydb`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artista_has_instrumento_instrumento1`
    FOREIGN KEY (`instrumento_idInstrumento`)
    REFERENCES `mydb`.`instrumento` (`idInstrumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banda_estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banda_estilo` (
  `banda_idBanda` INT NOT NULL,
  `estiloMusical_idEstiloMusical` INT NOT NULL,
  PRIMARY KEY (`banda_idBanda`, `estiloMusical_idEstiloMusical`),
  INDEX `fk_banda_has_estiloMusical_estiloMusical1_idx` (`estiloMusical_idEstiloMusical` ASC) VISIBLE,
  INDEX `fk_banda_has_estiloMusical_banda1_idx` (`banda_idBanda` ASC) VISIBLE,
  CONSTRAINT `fk_banda_has_estiloMusical_banda1`
    FOREIGN KEY (`banda_idBanda`)
    REFERENCES `mydb`.`banda` (`idBanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_banda_has_estiloMusical_estiloMusical1`
    FOREIGN KEY (`estiloMusical_idEstiloMusical`)
    REFERENCES `mydb`.`estiloMusical` (`idEstiloMusical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banda_artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banda_artista` (
  `artista_idArtista` INT NOT NULL,
  `banda_idBanda` INT NOT NULL,
  PRIMARY KEY (`artista_idArtista`, `banda_idBanda`),
  INDEX `fk_artista_has_banda_banda1_idx` (`banda_idBanda` ASC) VISIBLE,
  INDEX `fk_artista_has_banda_artista1_idx` (`artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_artista_has_banda_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `mydb`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artista_has_banda_banda1`
    FOREIGN KEY (`banda_idBanda`)
    REFERENCES `mydb`.`banda` (`idBanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
